services:
  frontend:
    build:
      context: ./frontend
    container_name: startup-frontend
    ports:
      - "8501:8501"  # Internal port for Streamlit
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro  # Mount custom Nginx config
    ports:
      - "80:80"  # Expose Nginx on port 80
    depends_on:
      - streamlit  # Reference the service name, not container_name
    networks:
      - app-network

networks:
  app-network:
    driver: bridge